### PR TITLE
Add Scala 3 support

### LINKED ISSUE #219: Migration on Scala 3
Currently, we are blocked on migration on Scala 3 due to a bug with `AnyVal`s: https://github.com/lampepfl/dotty/issues/11264
The obvious fix is dropping `AvyVal` for `Dual`, `Product` and `Sum`, but probably that will lead to performance issues.
Another [idea](https://github.com/typelevel/monoids/pull/147/files#r558808533) proposed by @ChristopherDavenport is using opaque types in Scala 3, and leave `AnyVal`s in Scala 2.

### PR DESCRIPTION
**Pull request by danicheg**
Closes #219 
This uses the idea of @ChristopherDavenport to use opaque types for Scala 3 and still use `AnyVal`s for Scala 2.

### CODE REVIEW

**Comment by rossabaker** [comment]
Why would tests be duplicated?

Can you have the companions extend some shared private trait to write to share them between the two implementations, and just have the core types duplicated?

A similar idea was floated in Cats for the monad transformers.  Those types have several functions that need to be duplicated, so I think that's an uglier problem, which is why it stalled.  Perhaps it's more tractable here.

**Comment by danicheg** [comment]
@rossabaker for some reason, that wasn't worked for me on the first try, but currently, we have only duplications for type definitions. Also, I've rewritten all types on using opaque types for Scala 3.

**Comment by danicheg** [comment]
@rossabaker I'd be extremely glad if you check this (as well as the same migration on Scala 3 for semigroups https://github.com/typelevel/semigroups/pull/212) :pray:

**Review by rossabaker — COMMENTED** [review]
I'm not very well educated on opaque types.

1. Do `,hashCode`, `.equals`, `.toString` pass through to the underlying implementation?  That's great for the first two. We'd see a difference in the `.toString`.
2. Are there any other important case class facilities we're losing?  You added `apply` and `unapply`.  We lose `Product`, which I don't think I've ever cared about other than MiMa errors.  What happens to `Serializable`?  (Until Spark gets on Scala 3, maybe nobody cares.)

I don't think any of these are dealbreakers.  I like the approach.  Just thinking about worst case scenarios.

**Comment by danicheg** [comment]
@rossabaker thanks for checking this. 
1. Yeah, `.toString` would change behaviour. We could preserve it, but should we? 
2. It seems opaque types implements `java.io.Serializable` under the hood - https://alvinalexander.com/scala/how-dotty-opaque-types-compile-to-java-jvm-code/.

**Comment by rossabaker** [comment]
@alexandru is operating in a similar space here with the monix-newtypes library.  I can't see that he's done anything about toString.  I wonder whether he has thoughts on whether it's worthwhile to try.

My gut feeling is that we should try to have `toString` reflect the new type, but I don't think it's a blocker.  I'm happy with this as is.

**Comment by danicheg** [comment]
@rossabaker am I correct, `.toString` that reflects the new type is just unwrapped value? Likewise `monix-newtypes` does https://scastie.scala-lang.org/UXai1TOHTwiszH7BOuxhfQ.

**Comment by rossabaker** [comment]
I think Scala 3 Monoids and Scala 2 Newtypes and Scala 3 Newtypes will just render `unwrappedValue` and Scala 2 Monoids will render `NameOfNewType(unwrappedValue)`?  I think I like the Scala 2 Monoids behavior, but I'm fine with the Newtypes behavior.  I think I would care more about consistency between the two, though it will be a chore on one side or the other.

**Comment by danicheg** [comment]
Ah, now I see the problem. You are right, Scala 2 Monoids `toString` will render as `NameOfNewType(unwrappedValue)` and Scala 3 NewTypes as `unwrappedValue`. Also, it seems, that we can't override `toString` for opaque types in Scala 3 (folks in Scala gitter didn't answer for now, but I am confident about it). So, we only can override the current behaviour of `toString` for Scala 2 Monoids to have it consistent for both Scala 2 and 3 :( And what's more, we will have varied behaviour for `show` and `toString`. Otherwise, we also should change it. Speaking for myself, I can't choose what's better in that case.

**Review by rossabaker — COMMENTED** [review]
Just to make sure I understand:

* Scala 2 toString: wraps, could be overridden to unwrap
* Scala 3 toString: unwrapped, no choice
* show: can do whatever, but toString is the easiest

If we want `show` and `toString` to be consistent across versions, unwrapped is the only option.  If we want to wrap it, we can get 3 out of 4 by providing wrapped `Show` instances.

This project is very Haskell-like, and Haskell wraps its monoid newtypes in its `Show` instances.  I think that's a good experience and have a mild preference for it.  I'm also not yet a user of this library and my opinion shouldn't matter much.

I think the important parts of this PR are good, and I think this bikeshed can be painted later if you just want to merge what's here,.

**Review by rossabaker — APPROVED** [review]

**Comment by danicheg** [comment]
Perhaps it's reasonable to add a few lines in docs about the behaviour of `toString` in Scala 2/3 and add suggestions on using `show` instead. What do you think @rossabaker?

**Review by rossabaker — APPROVED** [review]
Looks good

**Comment by danicheg** [comment]
@rossabaker thanks for your help on this! I added several lines about `toString()` behaviour in docs and that's the last what I planned to do here.

**Pull request merged**
